Laf 250/update category pages
msoeSE/legalAidFinder pull request #34
Opened 2018-05-03 02:41 UTC by hermanator608

2018-05-03 13:29 UTC, tphorbin commented on client/src/Admin/Category/CategoryModify.js
> +
Are these comments necessary?

2018-05-06 00:35 UTC, hermanator608 commented on client/src/Admin/Category/CategoryModify.js
> +
Good catch!

2018-05-06 18:11 UTC, triqp approved these changes

2018-05-07 19:10 UTC, wozniakbe approved these changes

2018-05-07 19:16 UTC, wozniakbe requested changes
Lots of scripts such as "npm start" got deleted, any reason?

2018-05-07 19:18 UTC, tphorbin commented
Not needed since we don’t actually have a server to start. It can be added back if you really want it

> On May 7, 2018, at 2:16 PM, Ben Wozniak <notifications@github.com> wrote:
> 
> @wozniakbe requested changes on this pull request.
> 
> Lots of scripts such as "npm start" got deleted, any reason?
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub <https://github.com/msoeSE/legalAidFinder/pull/34#pullrequestreview-118116055>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AQ5DvAyijHM5guq4a6SQtHVMI7GnCjYKks5twJ2ggaJpZM4TwbKC>.
>

2018-05-07 19:35 UTC, wozniakbe approved these changes
Tripp explained why scripts were removed, looks good

2018-05-07 20:05 UTC, muencha approved these changes

2018-05-07 20:31 UTC, merged